# Generated by Django 6.0.3 on 2026-03-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('data_entrega', models.DateTimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
