# Generated by Django 6.0.3 on 2026-03-28 18:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='professores',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'PROFESSOR'}, related_name='turmas_professor', to=settings.AUTH_USER_MODEL),
        ),
    ]
